---
title: "Schedule"
slug: schedule
---

```{r echo=FALSE,message=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(fontawesome)
```

## Table of Contents

```{r icontibble, echo=FALSE, message=FALSE}
faread <-  as.character(fa("book", fill = "#739670", height = "17px"))
falesson <-  as.character(fa("chalkboard", fill = "#764874", height = "17px"))
faexample <-  as.character(fa("lightbulb", fill = "#eb7b59", height = "17px"))
faass <- as.character(fa("tasks", fill = "#cf4647", height = "17px"))
fadue <- as.character(fa("folder-open", fill = "#2a6e84", height = "17px"))


tableofcontent <- tibble(
  
  type <- c("Readings", 
            "Data Camp",
            "Examples",
            "Tasks",
            "Due"),
  
  location <- c("[Go](/readings/)",
                "[Go](/datacamp/)",
                "[Go](/examples/)",
                "[Go](/tasks/)",
                "[Go](/due/)"),
  
  icon <- c(faread,
            falesson,
            faexample,
            faass,
            fadue),
  
  descr <- c("Weekly readings.",
             "R/RStudio Training modules created by Data Camp.",
             "Interactive R lessons and additional materials.",
             "Weekly tasks and deliverables.",
             "Weekly submission information."
             ),
  
  .name_repair = "minimal"

  ) 
```

<center>
```{r, echo=FALSE}
tableofcontent %>%
  kbl(col.names = NULL, 
      "html", 
      escape = FALSE,
      align = 'lccl') %>%
  column_spec(1, 
              bold = TRUE)
```
</center>

<span style="font-size:17px">*Note: Assignments are due by* ***the beginning of class time each Thursday at 4:00 PM*** *unless otherwise noted.*^[If we go online for whatever reason, then submissions will be due at the same time within the eCampus portal]</span>

<br>
<br>

<hr style"width:50%; margin-left:25% !important; margin-right:25% !important;" />

## Weekly Overview

`r blogdown::shortcode("schedule")`
