---
title: "Measures of Variability"
linktitle: "Week 4: Measures of Variability Content"
output:
  blogdown::html_page:
    toc: true
menu:
  materials:
    parent: Content
    weight: 4
type: docs
weight: 2
editor_options: 
  chunk_output_type: console
---

### Textbook Notes

- [Chapter 4 PowerPoint](/slides/Week 4/SSDS_Ch4.PPTX){target="_blank"}
- [Chapter 4 Lecture Notes](/lecture_notes/Week 4/SSDS_Ch4.docx){target="_blank"}

### In Class Notes
*posted during class time*

<!--
- Download the class slides: Click on the presentation itself and then you may

  + Move back and forth through the slideshow using the ⬅ and ⮕ buttons on your keyboard.
  + Press the letter **O** at any point to see see a tile view of the slideshow.
  + Use this [link](/slides/Week 2/Slides-Week-3.html){target="_blank"} to view a larger version of slideshow in a new window.

```{r echo = FALSE}
knitr::include_url("/slides/Week 3/Slides-Week-3.html")
```

You can download 

- a [PDF](/slides/Week 4/Slides-Week-4.pdf){target="_blank"} of the presentation. 
-->

### R Walkthrough
*posted during class time*

<!--
1. Download the data sets^[You will have to unzip this file. If you are unfamiliar with this process, please check the [Unzipping files](/resource/unzipping/) section under Resources for assistance.] and codebooks needed for this walkthrough. Put them wherever you want BUT please remember where they are.

- [Week 3 Walkthrough Materials](/slides/Week 4/Week4data.zip){target="_blank"}

2. Click on the presentation itself and then you may

- Move back and forth through the slideshow using the ⬅ and ⮕ buttons on your keyboard.
- Press the letter **O** at any point to see see a tile view of the slideshow.
- Use this [link](/slides/Week 4/Slides-Week-4.html){target="_blank"} to view a larger version of slideshow in a new window.

```{r echo = FALSE}
knitr::include_url("/slides/Week 4/Slides-Week-4.html")
```

You can download a [PDF](/slides/Week 4/Slides-Week-4.pdf){target="_blank"} of the presentation above. 
-->
