---
title: "Sampling and Sampling Distributions"
linktitle: "Week 7: Sampling and Sampling Distributions"
output:
  blogdown::html_page:
    toc: true
menu:
  materials:
    parent: Content
    weight: 5
type: docs
weight: 1
editor_options: 
  chunk_output_type: console
---

<script>
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>

<style>
  .hvr-sweep-to-left {
    display: inline-block;
    vertical-align: middle;
    -webkit-transform: perspective(1px) translateZ(0);
    transform: perspective(1px) translateZ(0);
    box-shadow: 0 0 1px rgba(0, 0, 0, 0);
    position: relative;
    -webkit-transition-property: color;
    transition-property: color;
    -webkit-transition-duration: 0.25s;
    transition-duration: 0.25s;
  }

.hvr-sweep-to-left:before {
  content: "";
  position: absolute;
  z-index: -1;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: #761756;
    -webkit-transform: scaleX(0);
  transform: scaleX(0);
  -webkit-transform-origin: 100% 50%;
  transform-origin: 100% 50%;
  -webkit-transition-property: transform;
  transition-property: transform;
  -webkit-transition-duration: 0.3s;
  transition-duration: 0.3s;
  -webkit-transition-timing-function: ease-out;
  transition-timing-function: ease-out;
}

.hvr-sweep-to-left:hover, .hvr-sweep-to-left:focus, .hvr-sweep-to-left:active {
  color: white;
}

.hvr-sweep-to-left:hover:before, .hvr-sweep-to-left:focus:before, .hvr-sweep-to-left:active:before {
  -webkit-transform: scaleX(1);
  transform: scaleX(1);
}
</style>

### Textbook Notes

- [Chapter 6 PowerPoint](/slides/Week 7/SSDS_Ch6.PPTX){target="_blank"}
- [Chapter 6 Lecture Notes](/lecture_notes/Week 7/SSDS_Ch6.docx){target="_blank"}


### In Class Notes

*posted during class time*
<!--


```{r echo = FALSE}
knitr::include_url("/slides/Week 7/Slides-Week-7.html")
```

You can move back and forth using <kbd>←</kbd> and <kbd>→</kbd> and toggle fullscreen by pressing <kbd>F</kbd>. Just press <kbd>O</kbd>^[For **O**verview] at any point in your slideshow and a display of all slides, called tile view, will appear. Click on a slide to go there or press <kbd>O</kbd> to exit tile view. For more options, press <kbd>H</kbd> for help.

Want to see a larger version of the presentation? Click this [link](/slides/Week 7/Slides-Week-7.html){target="_blank"}.
-->

### R Walkthrough
*posted during class time*
<!--
Download a copy of everything you need to follow along the walkthrough^[You will have to unzip this file. If you are unfamiliar with this process, please check the [Unzipping files](/resource/unzipping/) section under Resources for assistance]

``{r echo=FALSE,eval=TRUE,message=FALSE,purl=FALSE}
loc <- here::here("static", "slides", "Week 7",  "EDP613Week7RMaterials.zip")

downloadthis::download_file(
  path = loc,
  output_name = "Week 7 R Walkthrough Materials",
  button_label = "Download",
  button_type = "default",
  has_icon = TRUE,
  icon = "fa fa-save",
  class = "hvr-sweep-to-left"
  )
```

<br>
``{r echo = FALSE}
knitr::include_url("/slides/Week 7/Slides-Week-7R.html")
```

You can move back and forth using <kbd>←</kbd> and <kbd>→</kbd> and toggle fullscreen by pressing <kbd>F</kbd>. Just press <kbd>O</kbd>^[For **O**verview] at any point in your slideshow and a display of all slides, called tile view, will appear. Click on a slide to go there or press <kbd>O</kbd> to exit tile view. For more options, press <kbd>H</kbd> for help.

Want to see a larger version of the presentation? Click this [link](/slides/Week 7/Slides-Week-7R.html){target="_blank"}.
-->